service: nodejs-aws-lambda

provider:
  name: aws
  runtime: nodejs18.x
  profile: aaronGlikman

functions:
  app:
    handler: dist/app.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
      
plugins:
  - serverless-offline